---
# tasks file for stow

- git:
    repo: 'https://github.com/lisale0/Stow.git'
    dest: /home/ubuntu/Stow
    update: yes
    force: yes
    depth: 1

- name: Copying the upstart file
  copy:
    src: wellness.conf
    dest: /etc/init/wellness.conf
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Starting the Stow node service
  service:
    name: wellness
    state: started
